name: Release Packages
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      release_start:
        description: 'enter true to trigger release'
        required: true
      release_description: 
        description: 'Release description'
        required: true

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: release/${{ steps.vars.outputs.sha_short }}
          release_name: Release ${{ github.sha }}
          body: |
            Changes in this Release
            ${{ github.event.inputs.release_description }}
          draft: false
          prerelease: false
        if: ${{ github.ref == 'refs/heads/master' && github.event.inputs.release_start == 'true' }}
